kumuluzee:
  name: weather
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8084
    http:
      port: 8084
  helth:
    checks:
      data-source-helth-check:
        jndi-name: jdbc/WeatherDS
  rest-properties:
    healthy: true
  config:
      etcd:
        hosts: http://192.168.99.100:2379
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
      ttl: 20
      ping-interval: 15
  cors-filter:
      servlet:
        allow-origin: "*"