apiVersion: v1
kind: Service
metadata:
  name: hosting
  labels:
    app: hosting
spec:
  type: LoadBalancer
  ports:
  - name: server
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hosting