apiVersion: v1
kind: Service
metadata:
  name: users
  labels:
    app: users
spec:
  type: LoadBalancer
  ports:
  - name: server
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: users