apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - image: tvenko/users
        name: users
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-users:5432/users
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://169.51.13.134:32696
        livenessProbe:
          httpGet:
            path: /health
            port: server
          initialDelaySeconds: 20
          periodSeconds: 3
        ports:
        - containerPort: 8081
          name: server
          protocol: TCP