apiVersion: v1
kind: Service
metadata:
  name: transport
  labels:
    app: transport
spec:
  type: ClusterIP
  ports:
  - port: 8092
    protocol: TCP
    targetPort: 8092
  selector:
    app: transport