apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: transport-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: transport
    spec:
      containers:
      - image: bsircelj/transport
        name: transport
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://169.51.13.134:32696
        ports:
        - containerPort: 8092
          name: server
          protocol: TCP