kumuluzee:
  name: apartments
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  datasources:
    - jndi-name: jdbc/ApartmentsDS
      connection-url: jdbc:postgresql://192.168.99.100:5433/apartments
      username: dbuser
      password: postgres
      max-pool-size: 20
  config:
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
      ttl: 20
      ping-interval: 15
  health:
    checks:
      data-source-helth-check:
        jndi-name: jdbc/ApartmentsDS
  cors-filter:
    servlet:
      allow-origin: "*"
  rest-properties:
    healthy: true