apiVersion: v1
kind: Service
metadata:
  name: user-analysis
  labels:
    app: user-analysis
spec:
  type: ClusterIP
  ports:
  - port: 8091
    protocol: TCP
    targetPort: 8091
  selector:
    app: user-analysis