kumuluzee:
  name: support
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8086
    http:
      port: 8086
  datasources:
    - jndi-name: jdbc/FaqDS
      connection-url: jdbc:postgresql://192.168.99.100:5433/faq
      username: dbuser
      password: postgres
      max-pool-size: 20
  helth:
    checks:
      data-source-helth-check:
        jndi-name: jdbc/FaqDS
  rest-properties:
    healthy: true
  config:
      etcd:
        hosts: http://192.168.99.100:2379
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
      ttl: 20
      ping-interval: 15
  cors-filter:
      servlet:
        allow-origin: "*"