apiVersion: v1
kind: Service
metadata:
  name: apartments-analisys
  labels:
    app: apartments-analisys
spec:
  type: ClusterIP
  ports:
  - port: 8089
    protocol: TCP
    targetPort: 8089
  selector:
    app: apartments-analisys