apiVersion: v1
kind: Service
metadata:
  name: payments
  labels:
    app: payments
spec:
  type: ClusterIP
  ports:
  - port: 8089
    protocol: TCP
    targetPort: 8089
  selector:
    app: payments