apiVersion: v1
kind: Service
metadata:
  name: support
  labels:
    app: support
spec:
  type: LoadBalancer
  ports:
  - name: server
    port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    app: support