apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: support-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: support
    spec:
      containers:
      - image: tvenko/support
        name: support
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-users:5432/faq
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://169.51.13.134:32696
        ports:
        - containerPort: 8086
          name: server
          protocol: TCP