apiVersion: v1
kind: Service
metadata:
  name: attractions
  labels:
    app: attractions
spec:
  type: LoadBalancer
  ports:
  - name: server
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: attractions