version: "3"
                services:
                  postgres:
                    image: postgres:9.6.3
                    ports:
                      - 5432:5432
                    environment:
                      POSTGRES_USER: dbuser
                      POSTGRES_PASSWORD: postgres
                      POSTGRES_DB: users
                  users:
                    image: tvenko/users
                    ports:
                      - 8080:8081
                    environment:
                      KUMULUZEE_DATASOURCES0_CONNECTIONURL: jdbc:postgresql://postgres:5432/users
                    depends_on:
                      - postgres