kumuluzee:
  name: hostinganalysis
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8087
    http:
      port: 8083
  config:
    etcd:
      hosts: http://localhost:2379
  discovery:
    etcd:
      hosts: http://localhost:2379
  cors-filter:
    servlet:
      allow-origin: "*"
