kumuluzee:
  name: apartmentsanalysis
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8089
    http:
      port: 8089
  config:
    etcd:
      hosts: http://192.168.99.100:2379
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
  cors-filter:
    servlet:
      allow-origin: "*"
